language: node_js
cache: yarn
node_js:
  - 'stable'

install:
 - yarn

script:
 - if [ "$TRAVIS_PULL_REQUEST_BRANCH" = "staging" ]; then yarn run staging; fi
 - if [ "$TRAVIS_BRANCH" = "staging" ]; then yarn run staging:complete; fi
 - if [ "$TRAVIS_PULL_REQUEST_BRANCH" = "master" ]; then yarn run prod; fi
 - if [ "$TRAVIS_BRANCH" = "master" ]; then yarn run prod:complete; fi